repos:
    - repo: local
      hooks:
        - id: lint
          name: lint
          entry: poetry run flake8 .
          language: system
          always_run: true
          pass_filenames: false
    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
        - id: black
          additional_dependencies: ['click==8.0.4']
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
        - id: isort
          name: isort (python)
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: check-added-large-files